import { Router } from 'express';
import { authController } from '../controllers/auth.controller';
import { authMiddleware } from '../middleware/auth.middleware';
import { validate } from '../middleware/validate.middleware';
import { registerSchema, loginSchema, changePasswordSchema } from '../validators/auth.schema';
const router = Router();
router.post('/register', validate(registerSchema), authController.register);
router.post('/login', validate(loginSchema), authController.login);
router.get('/verify-email/:token', authController.verifyEmail);
router.use(authMiddleware);
router.post('/change-password', validate(changePasswordSchema), authController.changePassword);
router.post('/verification-email', authController.requestVerificationEmail);
export default router;
